env:
  browser: true
  es6: true
  node: true
  jest: true
extends: 
  - "eslint:recommended"
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"
parser: babel-eslint
plugins:
  - react
rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0